# Makefile for the analysis summary
# Patrick Pletscher
# 2003-02-09

analysis.pdf:	analysis.tex
		pdflatex analysis.tex; pdflatex analysis.tex

#analysis.pdf:	analysis.dvi
#		dvipdf analysis.dvi

#analysis.dvi: 	analysis.tex
#		latex analysis.tex
