# Makefile for the algebra summary
# Patrick Pletscher
# 2003-02-15

algebra.pdf:	algebra.tex
		pdflatex algebra.tex

#analysis.pdf:	analysis.dvi
#		dvipdf analysis.dvi

#analysis.dvi: 	analysis.tex
#		latex analysis.tex
